"""DDS v2 public API.

Core guarantees:
1. Missing inputs remain explicit; the system never fills them silently.
2. Structure, evidence, decision, and delivery gates reject unqualified output.
3. Every decision field exposes provenance and evidence-derived confidence.
"""

__version__ = "2.0.0"

from dds.contracts import (
    CONFIDENCE_LEVEL_LABELS,
    CONFIDENCE_WEIGHTS,
    EVIDENCE_TYPES,
    DataRequirement,
    EvidenceRecord,
    EvidenceType,
    FALLBACK_STRATEGIES,
    FIELD_DESCRIPTIONS,
    REPORT_GROUPS,
    REPORT_UNITS,
    SECTION_REQUIREMENTS,
    VALID_SECTION_IDS,
    ContractViolationError,
    FieldOrigin,
    ProjectContext,
    ReportRun,
    ResolutionStatus,
    ResolvedField,
    ResolvedStatus,
    SectionData,
    SectionResult,
    ValidationResult,
    build_evidence_confidence,
    compute_confidence_from_evidence,
    compute_empirical_confidence,
    compute_evidence_confidence,
    confidence_level,
    derive_evidence_dimensions,
    normalize_evidence_type,
)
from dds.agents import (
    AgentError,
    AgentMessage,
    AgentMessageBus,
    AgentResult,
    AgentStatus,
    AgentTask,
    BaseAgent,
    ContentGeneratorAgent,
    ContentWriterAgent,
    TASK_CONTENT_WRITING,
    UnsupportedNumericClaimError,
    DataCollectorAgent,
    DataOrchestratorAgent,
    OrchestratorAgent,
    QualityAuditorAgent,
    ReportExporterAgent,
    ResearchPlannerAgent,
    TASK_RESEARCH_PLANNING,
    RequirementAgent,
    create_agent_system,
    generate_report,
    run_report_sync,
)

__all__ = [
    "__version__",
    # 框架
    "REPORT_GROUPS",
    "REPORT_UNITS",
    "SECTION_REQUIREMENTS",
    "VALID_SECTION_IDS",
    # 证据
    "EVIDENCE_TYPES",
    "EvidenceType",
    "ResolvedStatus",
    "ResolutionStatus",
    "CONFIDENCE_LEVEL_LABELS",
    "CONFIDENCE_WEIGHTS",
    "normalize_evidence_type",
    "confidence_level",
    "compute_evidence_confidence",
    "compute_empirical_confidence",
    "build_evidence_confidence",
    "derive_evidence_dimensions",
    "compute_confidence_from_evidence",
    # 数据结构
    "FieldOrigin",
    "SectionData",
    "ProjectContext",
    "DataRequirement",
    "EvidenceRecord",
    "ResolvedField",
    "SectionResult",
    "ReportRun",
    "ValidationResult",
    "ContractViolationError",
    # 降级
    "FALLBACK_STRATEGIES",
    "FIELD_DESCRIPTIONS",
    # Agent API
    "AgentError",
    "AgentMessage",
    "AgentMessageBus",
    "AgentResult",
    "AgentStatus",
    "AgentTask",
    "BaseAgent",
    "OrchestratorAgent",
    "RequirementAgent",
    "DataCollectorAgent",
    "DataOrchestratorAgent",
    "ContentGeneratorAgent",
    "ContentWriterAgent",
    "UnsupportedNumericClaimError",
    "TASK_CONTENT_WRITING",
    "QualityAuditorAgent",
    "ReportExporterAgent",
    "ResearchPlannerAgent",
    "TASK_RESEARCH_PLANNING",
    "create_agent_system",
    "generate_report",
    "run_report_sync",
]
